<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Vishwanaths-MacBook-Pro.local" name="testNG_Package.TC1" tests="13" failures="1" timestamp="30 Oct 2018 17:07:48 GMT" time="0.053" errors="0">
  <testcase name="gropusTest10" time="0.002" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest1" time="0.010" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest9" time="0.002" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest7" time="0.001" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest4" time="0.001" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest6" time="0.004" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest2" time="0.005" classname="testNG_Package.TC1"/>
  <testcase name="gropusTes3" time="0.014" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest8" time="0.006" classname="testNG_Package.TC1"/>
  <testcase name="gropusTest5" time="0.002" classname="testNG_Package.TC1"/>
  <testcase name="C" time="0.002" classname="testNG_Package.TC1"/>
  <testcase name="B" time="0.000" classname="testNG_Package.TC1">
    <skipped/>
  </testcase> <!-- B -->
  <testcase name="A" time="0.004" classname="testNG_Package.TC1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testNG_Package.TC1.A(TC1.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- A -->
</testsuite> <!-- testNG_Package.TC1 -->
